<?php
return array (
  'WEB_PUBLIC_PATH' => 'static',//网站公共目录
  'DIR_UPLOAD_PATH' => 'uploads',
  'DIR_RESIZE_PATH' => 'resize',
  'DIR_MINI_PATH' => 'mini',
  'DIR_THUMB_PATH' => 'thumb',
  'DIR_ATTCH_PATH' => 'attach',
  'PIC_MINI_WIDTH' => '75',
  'PIC_MINI_HEIGHT' => '75',
  'PIC_THUMB_WIDTH' => '140',
  'PIC_THUMB_HEIGHT' => '98',
  'PIC_RESIZE_WIDTH' => '650',
  'PIC_RESIZE_HEIGHT' => '650',
  'LIST_BOARD_NUMBER' => '20',
  'LIST_GRID_NUMBER' => '21',
  'LIST_VIEW_NUMBER' => '10',
  'LIST_PICTURE_NUMBER' => '5',
  'PAGE_ROLLPAGE' => 5,
  'PAGE_LISTROWS' => 18,
  'SITE_TITLE' => '大家一起乐一下',
  'SITE_URL' => 'http://leyixia.cc',
  'SITE_DP_AUTHOR' => 'admin@leyix.cc',
  'SITE_KEYWORDS' => '乐一下,经典段子,经典语录 冷笑话,神回复,知乎神回复,爆笑评论,搞笑段子,神回复集锦冷笑话,最新冷笑话,冷笑话大全,leyixia,脑筋急转弯,冷幽默',
  'SITE_DESCRIPTION' => '乐一下是一个经典段子、经典语录以及经典冷笑话、经典搞笑短信、神回复、知乎神回复的收集网站。我们专注于分享网络最新段子、幽默小笑话等一切搞笑的能给您带来快乐的东西。',
  'SITE_FOOTER' => 'Copyright © 2014-2016',
  'SITE_ICP' => '闽ICP备15013751号-4',
  'DEFAULT_DATE_FORMAT' => 'Y-m-d',
  'DEFAULT_THEME' => 'Leyix',
  'THEME_LIST' => 'Leyix',
  'QQ_APPKEY' => '',
  'QQ_RETURN_DOMAIN' => '',
  'QQ_ZONE_ID' => '',
  'QQ_ZONE_KEY' => '',
  'SINA_APPKEY' => 'SINA_KEY',
  'SINA_RETURN_DOMAIN' => 'SINA_RETURN_URL',
  'CUSTOM_URL_DEPR' => '/',
  'CUSTOM_URL_SUFFIX' => '.html',
  'CUSTOM_URL_MODEL' => '2',
  'COMMENT_ON_OFF' => '1',
  'COMMENT_VERIFY' => '1',
  'COMMENT_VERIFY_ADV' => '0',
  'COMMENT_USER_NAME' => '1',
  'COMMENT_USER_EMAIL' => '1',
  'COMMENT_EXAMINATION' => '0',
  'COMMENT_LIST_COUNT' => '5',
  'COMMENT_TEXT_LENGTH' => '6',
  'COMMENT_TEXT_SENSITIVE' => '123
fuck
nima
擦
二货
去死吧',
);